#Import necessary libraries
import streamlit as st
from PIL import Image

st.header("Projects")
st.markdown("Over the summer, I have been working on a variety of data science projects that show off various skills I have learned throughout my my courses. These projects each consist the of data cleaning, Exploratory Data Analysis, Data Visualizaition, Data Analysis, Summarizing my findings, and future improvements.")
st.write("")

st.subheader("MyAnimeList Data Analysis (R-Studio)")
st.image("images/MyAnimeList_-_Full_Text_Logo.jpg")
st.markdown("This project included the exploration and analysis of a dataset pulled from Kaggle named Anime Dataset 2023 by the user Sajid.")
st.markdown("The following questions were addressed in Project:")
st.markdown("**1. Does Popularity influence the rating of an anime?**")
st.markdown("**2. If we made a multiple linear regression model of all the different types of media and there scores, what would it look like?**")
st.markdown("**3a. Create a predicitve model to see if the number of episodes can predict the score of an anime.**")
st.markdown("**3b. Conduct a T-test to see if episodes is a statistically significant predictor for scores.**")
st.markdown("**4. Fit a Multiple Linear regression model using the preidctors: Start Year, Type of Anime, # of Members, and the response variable, score. Which is the best model?**")
st.markdown("**5. Do people equally prefer the top 5 Anime studios?**")
st.markdown("**6. What trends/groups can we observe by clustering rank, popularity, episodes, and start year to score?**")
st.link_button("View the Full MyAnimeList Project", "https://github.com/Alexdxe/myanimelist-analysis", type= "secondary")


st.subheader("Spotify Data Analysis (Python)")
st.image("images/Spotify_Full_Logo_RGB_Green.png")
st.markdown("This project explored and anlayized a dataset pulled from Kaggle named Most Streamed Spotify Songs 2024, by Nidula Elgiriyewithana.")
st.markdown("The following questions were addressed in this project.")
st.markdown("**1a. Is there a correlation between Spotify Streams and Youtube Views?**")
st.markdown("**1b. Does Spotify Streams statistically influence the amount of YouTube Views?**")
st.markdown("**2a.Is there a linear relationship between Spotify Streams, Spotify Playlist Count and Popularity?**")
st.markdown("**2b. On Average, how off will the predictions of Spotify Streams be off by if given the predictors Spotify Playlist and Popularity?**")
st.markdown("**3.Can we improve the following model(Spotify Playlist Count, Spotify Popularity, Spotify Streams, Youtube Views, TikTok Views) by projecting features into fewer dimensions?**")
st.link_button("View the Full Spotify Project", "https://github.com/Alexdxe/spotify-analysis", type= "secondary")

st.subheader("Keyboard Self-Study")
st.image("images/2702.jpg")
st.markdown("<h10 style>Image pulled from kbd.news </h10>", unsafe_allow_html=True)
st.markdown("<h4 style>This project consisted of two parts:</h4>", unsafe_allow_html=True)
st.write("")

st.markdown("<h5 style>Part 1 (Statistics): </h5>", unsafe_allow_html=True)
st.markdown("This part included the self-collection of data through random subjects and the conduction of a match paired t-test. The data was collected through random subjects within San Francisco's Japantown, where through a well-planned experiment, wanted to see if it could answer:")
st.markdown("**Do Tactile Mechanical Keyboard Switches Improve Your Words per Minute in Comparison to Linear Switches?**")
st.link_button("View the Full 1st Part of the Keyboard Project", "https://github.com/Alexdxe/keyboard-selfstudy/tree/main/Part%201", type= "secondary")
st.write("")

st.markdown("<h5 style>Part 2 (SQL, Python): </h5>", unsafe_allow_html=True)
st.markdown("This part included the sampling of 13 different keyboard switches, 950 different typing tests, and the use of 2 different programming languages. The idea of the project was to test and see if different keyboard switches(measuring various metrics like price, pitch(DB), weight and more) would affect the WPM and accuracy, explore the various relationships between predictors, and build predictive models.")
st.markdown("The questions were addressed in this project:")
st.markdown("**1. Is there a correlation between Weight and Average WPM??**")
st.markdown("**2. Construct a 95% Confidence Interval for Average WPM.**")
st.markdown("**3. Is there a relationship between dates and Average WPM/Accuracy?**")
st.markdown("**4. Can we predict the WPM of a switch based on Loudness, Enjoyment, Weight, Sound, and Tactility?**")
st.markdown("**5. Does a more expensive switch lead to a high WPM?**")
st.markdown("**6. Can I classify if a switch is Tactile based on WPM, Accuracy, and Price?**")
st.link_button("View the Full 2nd Part of the Keyboard Project", "https://github.com/Alexdxe/keyboard-selfstudy/tree/main/Part%202", type= "secondary")
st.markdown("**Click on Part 2 for the most recent attempt!**")
st.write("")

st.markdown("<h10 style>Note: This part of the project took 2 seperate attempts to complete.</h10>", unsafe_allow_html=True)
st.link_button("Original Attempt at Part 2", "https://github.com/Alexdxe/keyboard-selfstudy/tree/main/Part%202/Attempt%201", type= "secondary")
